#!/bin/sh

# Set repeat key rate for the whole system and mouse sensitivity
xset r rate 300 50 && xinput set-prop 'Logitech G203 LIGHTSYNC Gaming Mouse' 'libinput Accel Speed' -0.4
# Disable all mouse acceleration profiles (fucking annoying bullshit)
xinput set-prop 11 "libinput Accel Profile Enabled" 0, 0, 0
xinput set-prop 11 "libinput Accel Speed" 0
